services:
  api:
    build: .
    container_name: flowershop-api
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    container_name: flowershop-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
